client_homepage:
    path:     /
    defaults: { _controller: ClientBundle:Default:index }

client_profile:
    path:     /profile
    defaults: { _controller: ClientBundle:Client:profile }

client_changer_photo_profile:
    path:     /profile/photo
    defaults: { _controller: ClientBundle:Client:changerPhotoProfile }

client_changer_infos_profile:
    path:     /profile/infos
    defaults: { _controller: ClientBundle:Client:changerInfosProfile }

# Client routes
client_location_liste_voiture:
    path:     /location/voitures
    defaults: { _controller: ClientBundle:Client:listeVoituresLocation }

client_location_details_voiture:
    path:     /location/voitures/{id}
    defaults: { _controller: ClientBundle:Client:detailsVoituresLocation }

client_location_reserver_voiture:
    path:     /location/voitures/reserver/{id}
    defaults: { _controller: ClientBundle:Client:reserverVoituresLocation }


# Manager location routes
manager_location_register:
    path:     /register/manager/location
    defaults: { _controller: ClientBundle:Registration:registerManagerLocation }

manager_location_ajouter_voiture:
    path:     /manager/location/voiture/ajouter
    defaults: { _controller: ClientBundle:Voiture:ajouter }

manager_location_list_voiture:
    path:     /manager/location/voiture/afficher
    defaults: { _controller: ClientBundle:Voiture:afficher }

manager_location_supprimer_voiture:
    path:     /manager/location/voiture/supprimer/{id}
    defaults: { _controller: ClientBundle:Voiture:supprimer }

manager_location_modifier_voiture:
    path:     /manager/location/voiture/modifier/{id}
    defaults: { _controller: ClientBundle:Voiture:modifier }

manager_location_ajouter_chauffeur:
    path:     /manager/location/chauffeur/ajouter
    defaults: { _controller: ClientBundle:Chauffeur:ajouter }

manager_location_afficher_chauffeur:
    path:     /manager/location/chauffeur/afficher
    defaults: { _controller: ClientBundle:Chauffeur:afficher }

manager_location_supprimer_chauffeur:
    path:     /manager/location/chauffeur/supprimer/{id}
    defaults: { _controller: ClientBundle:Chauffeur:supprimer }

manager_location_modifier_chauffeur:
    path:     /manager/location/chauffeur/modifier/{id}
    defaults: { _controller: ClientBundle:Chauffeur:modifier }


# ADMIN Routes
admin_afficher_demandes_agences:
    path:     /admin/agences/demandes
    defaults: { _controller: ClientBundle:Admin:afficherDemandesAgences }

admin_supprimer_demandes_agences:
    path:     /admin/agences/demandes/supprimer/{id}
    defaults: { _controller: ClientBundle:Admin:SupprimerDemandesAgences }

admin_approuver_demandes_agences:
    path:     /admin/agences/demandes/approuver/{id}
    defaults: { _controller: ClientBundle:Admin:approuverDemandesAgences }

admin_agences_afficher:
    path:     /admin/agences/afficher
    defaults: { _controller: ClientBundle:Admin:afficherToutesAgences }

admin_supprimer_agence:
    path:     /admin/agences/supprimer/{id}
    defaults: { _controller: ClientBundle:Admin:SupprimerAgence }
